version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows
      - /.github/actions/setup
    target-branch: next
    schedule:
      interval: monthly
      timezone: Europe/Amsterdam
      time: '06:00'
    groups:
      github_actions:
        patterns:
          - '*'
          
  - package-ecosystem: npm
    directory: /
    target-branch: next
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Amsterdam
      time: '06:00'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
