/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    organizations: Organization;
    'story-universes': StoryUniverse;
    stories: Story;
    'story-chapters': StoryChapter;
    characters: Character;
    'story-nodes': StoryNode;
    'story-events': StoryEvent;
    'plugin-ai-instructions': PluginAiInstruction;
    'plugin-ai-ai-jobs': PluginAiAiJob;
    users: User;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'story-universes': StoryUniversesSelect<false> | StoryUniversesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    'story-chapters': StoryChaptersSelect<false> | StoryChaptersSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'story-nodes': StoryNodesSelect<false> | StoryNodesSelect<true>;
    'story-events': StoryEventsSelect<false> | StoryEventsSelect<true>;
    'plugin-ai-instructions': PluginAiInstructionsSelect<false> | PluginAiInstructionsSelect<true>;
    'plugin-ai-ai-jobs': PluginAiAiJobsSelect<false> | PluginAiAiJobsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'ai-providers': AiSetting;
  };
  globalsSelect: {
    'ai-providers': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Organizations are used to scope Storytelling content. Users associated with an organization can only access their own org data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * Unique identifier for the organization (used in URLs and references).
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-universes".
 */
export interface StoryUniverse {
  id: number;
  /**
   * Owning organization. Access is scoped by this value.
   */
  organization: number | Organization;
  /**
   * Unique key used in URLs and engine references.
   */
  slug: string;
  /**
   * Short universe title. Use AI Compose to ideate and refine.
   */
  title: string;
  /**
   * Longer background / context for this universe. Rich text with AI Compose enabled.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional universe-wide flags or engine parameters.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  /**
   * Owning organization. Access is scoped by this value.
   */
  organization: number | Organization;
  /**
   * Optional universe this story belongs to (Episode 1, 2, etc).
   */
  universe?: (number | null) | StoryUniverse;
  /**
   * Unique key for URLs and game engine references.
   */
  slug: string;
  /**
   * Short story title. Use AI Compose to ideate options.
   */
  title: string;
  /**
   * Short abstract explaining the story in a nutshell. AI Compose is enabled to draft this quickly.
   */
  summary?: string | null;
  /**
   * High-level quest description for players. AI Compose can propose clear, actionable goals.
   */
  objective?: string | null;
  status: 'draft' | 'active' | 'archived';
  /**
   * Ordered list of chapters in this story. Create chapters and link them here or from the chapter itself.
   */
  chapters?: (number | StoryChapter)[] | null;
  /**
   * Optional internal classification labels.
   */
  tags?: string[] | null;
  /**
   * Optional engine-specific metadata.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-chapters".
 */
export interface StoryChapter {
  id: number;
  /**
   * Owning organization. Access is scoped by this value.
   */
  organization: number | Organization;
  /**
   * Parent story for this chapter.
   */
  story: number | Story;
  /**
   * Integer index indicating chapter order within the story.
   */
  order: number;
  /**
   * Short chapter title. Use AI Compose to ideate concise titles.
   */
  title: string;
  /**
   * Short recap of the chapter. Use AI Compose to quickly draft an overview.
   */
  summary?: string | null;
  /**
   * Narrative content. Rich text supports headings, lists, and inline images. AI Compose is enabled.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For planning and scheduling game sessions.
   */
  estimatedDurationMinutes?: number | null;
  /**
   * Optional engine-specific data for this chapter.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  /**
   * The organization that owns this NPC.
   */
  organization?: (number | null) | Organization;
  /**
   * URL safe identifier used by APIs and the game engine.
   */
  slug: string;
  /**
   * The name players will see for this NPC.
   */
  name: string;
  /**
   * High level function of this NPC in the story.
   */
  role: 'guide' | 'rival' | 'historian' | 'narrator' | 'merchant' | 'scholar' | 'other';
  /**
   * Very short description used in UI and in prompts.
   */
  description?: string | null;
  /**
   * Gender presentation of the character.
   */
  gender?: string | null;
  /**
   * Approximate perceived age.
   */
  ageRange?: string | null;
  ethnicity?: string | null;
  skinTone?: string | null;
  faceShape?: string | null;
  eyeShape?: string | null;
  eyeColor?: string | null;
  eyebrows?: string | null;
  nose?: string | null;
  lips?: string | null;
  distinguishingFeatures?: string | null;
  hairLength?: string | null;
  hairTexture?: string | null;
  hairStyle?: string | null;
  hairColor?: string | null;
  era?: string | null;
  culture?: string | null;
  clothingStyle?: string | null;
  palette?: string | null;
  expression?: string | null;
  vibe?: string | null;
  posture?: string | null;
  /**
   * 2D portrait image used for UI/dialogue.
   */
  portrait?: (number | null) | Media;
  /**
   * Optional 3D model reference. Can be replaced with a dedicated assets collection later.
   */
  model3D?: (number | null) | Media;
  /**
   * Generate character speech sample
   */
  Speech?: (number | null) | Media;
  /**
   * A longer biography/personality profile. Use AI Compose to generate consistent backstory and voice.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Stories this NPC appears in (many-to-many).
   */
  linkedStories?: (number | Story)[] | null;
  /**
   * Mark as a library NPC that can be reused across experiences for the same organization.
   */
  reusableAcrossHunts?: boolean | null;
  /**
   * Optional engine metadata (dialogue IDs, voice actor ID, behavior flags, etc).
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-nodes".
 */
export interface StoryNode {
  id: number;
  /**
   * Owning organization. Access is scoped by this value.
   */
  organization: number | Organization;
  /**
   * Story this node belongs to.
   */
  story: number | Story;
  /**
   * Optional chapter association; lets engines map nodes to linear content when needed.
   */
  chapter?: (number | null) | StoryChapter;
  /**
   * Self-reference to parent; enables tree-like structures.
   */
  parentNode?: (number | null) | StoryNode;
  /**
   * Ordering among sibling nodes for deterministic traversal.
   */
  order?: number | null;
  /**
   * Controls how the engine treats this node (narration, choice, condition, or ending).
   */
  nodeType: 'narration' | 'choice' | 'condition' | 'ending';
  /**
   * Short node title; useful for editors and visual graphs. AI Compose enabled.
   */
  title?: string | null;
  /**
   * Narrative shown to the player. Rich text with AI Compose to draft/iterate fast.
   */
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional short label shown in UI when nodeType is "choice". AI can suggest succinct options.
   */
  choiceLabel?: string | null;
  /**
   * Optional JSON used by the game engine to decide transitions (e.g., flags/variables checks).
   */
  conditionExpression?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Outgoing edges for this node (branching).
   */
  nextNodes?: (number | StoryNode)[] | null;
  /**
   * Optional engine-specific data for this node.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Analytics and telemetry events for stories. Designed for internal tools and dashboards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-events".
 */
export interface StoryEvent {
  id: number;
  /**
   * Owning organization. Access is scoped by this value.
   */
  organization: number | Organization;
  story: number | Story;
  chapter?: (number | null) | StoryChapter;
  npc?: (number | null) | Character;
  /**
   * Example values: story_intro_viewed, story_intro_skipped, npc_interaction, chapter_completed, drop_off
   */
  eventType: string;
  /**
   * Arbitrary event data (shape defined by your game engine/services).
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions".
 */
export interface PluginAiInstruction {
  id: number;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'schema-path'?: string | null;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'field-type'?: ('text' | 'textarea' | 'upload' | 'richText') | null;
  'relation-to'?: string | null;
  'model-id'?: ('text' | 'richtext' | 'image' | 'tts' | 'video') | null;
  /**
   * Please reload your collection after applying the changes
   */
  disabled?: boolean | null;
  /**
   * Click 'Compose' to run this custom prompt and generate content
   */
  prompt?: string | null;
  images?:
    | {
        /**
         * Please make sure the image is publicly accessible.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  system?: string | null;
  layout?: string | null;
  'text-settings'?: {
    provider?: string | null;
    model?: string | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  'richtext-settings'?: {
    provider?: string | null;
    model?: string | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  'image-settings'?: {
    provider?: string | null;
    model?: string | null;
  };
  'tts-settings'?: {
    provider?: string | null;
    model?: string | null;
    voice?: ('alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer') | null;
    response_format?: ('mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm') | null;
    speed?: number | null;
    stability?: number | null;
    similarity_boost?: number | null;
    style?: number | null;
    use_speaker_boost?: boolean | null;
    seed?: number | null;
    previous_text?: string | null;
    next_text?: string | null;
  };
  'video-settings'?: {
    mode?: ('t2v' | 'i2v') | null;
    falModelId?: ('fal-ai/minimax-video' | 'fal-ai/hunyuan-video' | 'fal-ai/luma-dream-machine') | null;
    width?: number | null;
    height?: number | null;
    durationSeconds?: number | null;
    fps?: number | null;
    seed?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-ai-jobs".
 */
export interface PluginAiAiJob {
  id: number;
  instructionId: number | PluginAiInstruction;
  task_id: string;
  status?: ('queued' | 'running' | 'completed' | 'failed' | 'canceled') | null;
  progress?: number | null;
  result_id?: string | null;
  error?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'story-universes';
        value: number | StoryUniverse;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'story-chapters';
        value: number | StoryChapter;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'story-nodes';
        value: number | StoryNode;
      } | null)
    | ({
        relationTo: 'story-events';
        value: number | StoryEvent;
      } | null)
    | ({
        relationTo: 'plugin-ai-instructions';
        value: number | PluginAiInstruction;
      } | null)
    | ({
        relationTo: 'plugin-ai-ai-jobs';
        value: number | PluginAiAiJob;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-universes_select".
 */
export interface StoryUniversesSelect<T extends boolean = true> {
  organization?: T;
  slug?: T;
  title?: T;
  summary?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  organization?: T;
  universe?: T;
  slug?: T;
  title?: T;
  summary?: T;
  objective?: T;
  status?: T;
  chapters?: T;
  tags?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-chapters_select".
 */
export interface StoryChaptersSelect<T extends boolean = true> {
  organization?: T;
  story?: T;
  order?: T;
  title?: T;
  summary?: T;
  content?: T;
  estimatedDurationMinutes?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  organization?: T;
  slug?: T;
  name?: T;
  role?: T;
  description?: T;
  gender?: T;
  ageRange?: T;
  ethnicity?: T;
  skinTone?: T;
  faceShape?: T;
  eyeShape?: T;
  eyeColor?: T;
  eyebrows?: T;
  nose?: T;
  lips?: T;
  distinguishingFeatures?: T;
  hairLength?: T;
  hairTexture?: T;
  hairStyle?: T;
  hairColor?: T;
  era?: T;
  culture?: T;
  clothingStyle?: T;
  palette?: T;
  expression?: T;
  vibe?: T;
  posture?: T;
  portrait?: T;
  model3D?: T;
  Speech?: T;
  bio?: T;
  linkedStories?: T;
  reusableAcrossHunts?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-nodes_select".
 */
export interface StoryNodesSelect<T extends boolean = true> {
  organization?: T;
  story?: T;
  chapter?: T;
  parentNode?: T;
  order?: T;
  nodeType?: T;
  title?: T;
  text?: T;
  choiceLabel?: T;
  conditionExpression?: T;
  nextNodes?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-events_select".
 */
export interface StoryEventsSelect<T extends boolean = true> {
  organization?: T;
  story?: T;
  chapter?: T;
  npc?: T;
  eventType?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions_select".
 */
export interface PluginAiInstructionsSelect<T extends boolean = true> {
  'schema-path'?: T;
  'field-type'?: T;
  'relation-to'?: T;
  'model-id'?: T;
  disabled?: T;
  prompt?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  system?: T;
  layout?: T;
  'text-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  'richtext-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  'image-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
      };
  'tts-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        voice?: T;
        response_format?: T;
        speed?: T;
        stability?: T;
        similarity_boost?: T;
        style?: T;
        use_speaker_boost?: T;
        seed?: T;
        previous_text?: T;
        next_text?: T;
      };
  'video-settings'?:
    | T
    | {
        mode?: T;
        falModelId?: T;
        width?: T;
        height?: T;
        durationSeconds?: T;
        fps?: T;
        seed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-ai-jobs_select".
 */
export interface PluginAiAiJobsSelect<T extends boolean = true> {
  instructionId?: T;
  task_id?: T;
  status?: T;
  progress?: T;
  result_id?: T;
  error?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-providers".
 */
export interface AiSetting {
  id: number;
  /**
   * Configure which AI providers to use and their settings
   */
  providers: (
    | {
        enabled?: boolean | null;
        /**
         * Optional. If empty, @ai-sdk/openai will use the OPENAI_API_KEY environment variable.
         */
        apiKey?: string | null;
        /**
         * Optional. Override default API endpoint (defaults to https://api.openai.com/v1).
         */
        baseURL?: string | null;
        /**
         * Optional. OpenAI organization ID for billing and access control.
         */
        organization?: string | null;
        /**
         * Optional. OpenAI project ID for organization-level access.
         */
        project?: string | null;
        /**
         * Optional. Extra headers to send with every request, for example routing through a proxy.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Keep this list short. Enable only the models you actually use.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: ('text' | 'image' | 'tts' | 'embedding') | null;
              /**
               * Controls randomness. 0 = deterministic, 2 = very creative.
               */
              temperature?: number | null;
              /**
               * Maximum number of tokens to generate. Leave empty for model default.
               */
              maxTokens?: number | null;
              /**
               * Nucleus sampling probability threshold.
               */
              topP?: number | null;
              /**
               * Penalize tokens based on frequency in the text.
               */
              frequencyPenalty?: number | null;
              /**
               * Penalize tokens based on presence in the text.
               */
              presencePenalty?: number | null;
              /**
               * Optional. Seed for deterministic sampling.
               */
              seed?: number | null;
              /**
               * Modify likelihood of tokens (JSON object mapping token IDs to bias).
               */
              logitBias?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              /**
               * Image dimensions.
               */
              size?: ('1024x1024' | '1024x1792' | '1792x1024') | null;
              /**
               * Image quality (DALL-E 3 only).
               */
              quality?: ('standard' | 'hd') | null;
              /**
               * Image style (DALL-E 3 only).
               */
              style?: ('vivid' | 'natural') | null;
              /**
               * Voice for text-to-speech.
               */
              voice?: ('alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer') | null;
              /**
               * Speed of speech (0.25 to 4.0).
               */
              speed?: number | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openai';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your Anthropic API key. Will be encrypted in the database.
         */
        apiKey: string;
        models?:
          | {
              id: string;
              name: string;
              useCase?: 'text' | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'anthropic';
      }
    | {
        enabled?: boolean | null;
        /**
         * Optional. If empty, @ai-sdk/google will use the GOOGLE_GENERATIVE_AI_API_KEY environment variable.
         */
        apiKey?: string | null;
        /**
         * Optional. Override default API endpoint (defaults to https://generativelanguage.googleapis.com/v1beta).
         */
        baseURL?: string | null;
        /**
         * Optional. Extra headers to send with every request, for example routing through a proxy.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Keep this list short. Enable only the models you actually use.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: ('text' | 'image' | 'embedding') | null;
              /**
               * Controls randomness. 0 = deterministic, 2 = very creative.
               */
              temperature?: number | null;
              /**
               * Optional upper limit for generated tokens. Leave empty to let the SDK decide.
               */
              maxTokens?: number | null;
              /**
               * Nucleus sampling probability threshold.
               */
              topP?: number | null;
              /**
               * Limit sampling to the K most probable tokens.
               */
              topK?: number | null;
              /**
               * Gemini models that support it can return text, images, or both. Leave empty for text only.
               */
              responseModalities?: ('TEXT' | 'IMAGE')[] | null;
              /**
               * Used as imageConfig.aspectRatio for models that support it.
               */
              aspectRatio?: ('1:1' | '2:3' | '3:2' | '3:4' | '4:3' | '4:5' | '5:4' | '9:16' | '16:9' | '21:9') | null;
              /**
               * Imagen models option. Controls whether people can be generated.
               */
              personGeneration?: ('allow_adult' | 'allow_all' | 'dont_allow') | null;
              /**
               * For Gemini 3 models. Controls depth of reasoning.
               */
              thinkingLevel?: ('low' | 'high') | null;
              /**
               * Approx token budget for thinking step. For Gemini 2.5 models.
               */
              thinkingBudget?: number | null;
              /**
               * If true, exposes high level reasoning summaries in the response metadata.
               */
              includeThoughts?: boolean | null;
              safetySettings?:
                | {
                    category:
                      | 'HARM_CATEGORY_HARASSMENT'
                      | 'HARM_CATEGORY_HATE_SPEECH'
                      | 'HARM_CATEGORY_SEXUALLY_EXPLICIT'
                      | 'HARM_CATEGORY_DANGEROUS_CONTENT';
                    threshold: 'BLOCK_NONE' | 'BLOCK_LOW_AND_ABOVE' | 'BLOCK_MEDIUM_AND_ABOVE' | 'BLOCK_ONLY_HIGH';
                    id?: string | null;
                  }[]
                | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'google';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your xAI API key. Will be encrypted in the database.
         */
        apiKey: string;
        models?:
          | {
              id: string;
              name: string;
              useCase: 'text' | 'image';
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'xai';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your ElevenLabs API key. Will be encrypted in the database. Get yours at elevenlabs.io
         */
        apiKey: string;
        /**
         * Optional. Override default API endpoint (defaults to https://api.elevenlabs.io/v1).
         */
        baseURL?: string | null;
        /**
         * Optional. Custom headers to send with every request.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Use the "Fetch Voices" button above to populate this list from your ElevenLabs account.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
              category?: ('premade' | 'cloned' | 'professional' | 'generated') | null;
              preview_url?: string | null;
              /**
               * Voice attributes like gender, age, accent (JSON object). Example: {"gender": "female", "age": "young", "accent": "american"}
               */
              labels?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
            }[]
          | null;
        /**
         * Configure TTS models with specific voice settings and parameters.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: 'tts' | null;
              enabled?: boolean | null;
              /**
               * Voice stability (0-1). Lower = more emotional range, higher = more monotonous.
               */
              stability?: number | null;
              /**
               * How closely AI adheres to the original voice (0-1).
               */
              similarity_boost?: number | null;
              /**
               * Amplify speaker style (0-1). Values above 0 may increase latency.
               */
              style?: number | null;
              /**
               * Boost similarity to original speaker (increases latency).
               */
              use_speaker_boost?: boolean | null;
              /**
               * ISO 639-1 language code (only for Turbo v2.5 and Flash v2.5).
               */
              language_code?: string | null;
              /**
               * Seed for deterministic sampling (0-4294967295).
               */
              seed?: number | null;
              /**
               * Controls text normalization (spell out numbers, etc.)
               */
              apply_text_normalization?: ('auto' | 'on' | 'off') | null;
              /**
               * Language-specific normalization (e.g., Japanese). May increase latency.
               */
              apply_language_text_normalization?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'elevenlabs';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your Fal API key. Will be encrypted in the database.
         */
        apiKey: string;
        /**
         * Secret for webhook verification (optional)
         */
        webhookSecret?: string | null;
        models?:
          | {
              id: string;
              name: string;
              useCase: 'image' | 'video';
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fal';
      }
    | {
        /**
         * Display name for this custom provider (e.g., "Ollama", "Together AI")
         */
        providerName: string;
        enabled?: boolean | null;
        /**
         * API key for this provider (if required)
         */
        apiKey: string;
        /**
         * OpenAI-compatible API endpoint (e.g., http://localhost:11434/v1)
         */
        baseURL: string;
        models?:
          | {
              id: string;
              name: string;
              useCase: 'text' | 'image' | 'video' | 'tts';
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openai-compatible';
      }
  )[];
  /**
   * Default provider/model for each use case
   */
  defaults?: {
    text?: {
      /**
       * Auto-populated from blocks
       */
      provider?: string | null;
      model?: string | null;
    };
    image?: {
      provider?: string | null;
      model?: string | null;
    };
    video?: {
      provider?: string | null;
      model?: string | null;
    };
    tts?: {
      provider?: string | null;
      model?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-providers_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  providers?:
    | T
    | {
        openai?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              organization?: T;
              project?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    temperature?: T;
                    maxTokens?: T;
                    topP?: T;
                    frequencyPenalty?: T;
                    presencePenalty?: T;
                    seed?: T;
                    logitBias?: T;
                    size?: T;
                    quality?: T;
                    style?: T;
                    voice?: T;
                    speed?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        anthropic?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        google?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    temperature?: T;
                    maxTokens?: T;
                    topP?: T;
                    topK?: T;
                    responseModalities?: T;
                    aspectRatio?: T;
                    personGeneration?: T;
                    thinkingLevel?: T;
                    thinkingBudget?: T;
                    includeThoughts?: T;
                    safetySettings?:
                      | T
                      | {
                          category?: T;
                          threshold?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        xai?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        elevenlabs?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                    category?: T;
                    preview_url?: T;
                    labels?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                    stability?: T;
                    similarity_boost?: T;
                    style?: T;
                    use_speaker_boost?: T;
                    language_code?: T;
                    seed?: T;
                    apply_text_normalization?: T;
                    apply_language_text_normalization?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fal?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              webhookSecret?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'openai-compatible'?:
          | T
          | {
              providerName?: T;
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  defaults?:
    | T
    | {
        text?:
          | T
          | {
              provider?: T;
              model?: T;
            };
        image?:
          | T
          | {
              provider?: T;
              model?: T;
            };
        video?:
          | T
          | {
              provider?: T;
              model?: T;
            };
        tts?:
          | T
          | {
              provider?: T;
              model?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'stories';
      value: number | Story;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}