/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    products: Product;
    'plugin-ai-instructions': PluginAiInstruction;
    'plugin-ai-ai-jobs': PluginAiAiJob;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'plugin-ai-instructions': PluginAiInstructionsSelect<false> | PluginAiInstructionsSelect<true>;
    'plugin-ai-ai-jobs': PluginAiAiJobsSelect<false> | PluginAiAiJobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'ai-providers': AiProvider;
  };
  globalsSelect: {
    'ai-providers': AiProvidersSelect<false> | AiProvidersSelect<true>;
  };
  locale: 'en' | 'es';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * URL safe identifier used by APIs and the game engine.
   */
  slug: string;
  /**
   * The name customers will see for this t-shirt design.
   */
  name: string;
  /**
   * A bold retro tiger with “Stay Wild” typography.
   */
  artworkDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  artwork?: (number | Media)[] | null;
  /**
   * A lifestyle shot of a model wearing the t-shirt in an urban skatepark.
   */
  mockupDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mockups?: (number | Media)[] | null;
  price: number;
  sizes?: ('xs' | 's' | 'm' | 'l' | 'xl' | 'xxl')[] | null;
  colors?: ('black' | 'white' | 'navy' | 'heather-grey' | 'olive' | 'burgundy')[] | null;
  /**
   * E.g., Oversized Fit, Regular Fit
   */
  fit?: string | null;
  /**
   * A complete design brief and production notes. Use AI Compose to generate variants, print guidance, and listing copy.
   */
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customize how AI interacts with specific fields within your enabled collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions".
 */
export interface PluginAiInstruction {
  id: number;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'schema-path'?: string | null;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'field-type'?: ('text' | 'textarea' | 'upload' | 'richText' | 'array') | null;
  'relation-to'?: string | null;
  hasMany?: boolean | null;
  'model-id'?: ('text' | 'richtext' | 'image' | 'tts' | 'array') | null;
  /**
   * Please reload your collection after applying the changes
   */
  disabled?: boolean | null;
  /**
   * Compose button will always be visible without requiring field focus
   */
  alwaysShow?: boolean | null;
  /**
   * If enabled, generated values are appended to current values instead of replacing them.
   */
  appendGenerated?: boolean | null;
  /**
   * Click 'Compose' to run this custom prompt and generate content
   */
  prompt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        /**
         * Please make sure the image is publicly accessible.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  system?: string | null;
  layout?: string | null;
  'text-settings'?: {
    provider?: string | null;
    model?: string | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'richtext-settings'?: {
    provider?: string | null;
    model?: string | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'image-settings'?: {
    provider?: string | null;
    model?: string | null;
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'tts-settings'?: {
    provider?: string | null;
    model?: string | null;
    voice?: string | null;
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  'array-settings'?: {
    provider?: string | null;
    model?: string | null;
    /**
     * Number of items to generate
     */
    count?: number | null;
    providerOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-ai-jobs".
 */
export interface PluginAiAiJob {
  id: number;
  instructionId: number | PluginAiInstruction;
  task_id: string;
  status?: ('queued' | 'running' | 'completed' | 'failed' | 'canceled') | null;
  progress?: number | null;
  result_id?: string | null;
  error?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'plugin-ai-instructions';
        value: number | PluginAiInstruction;
      } | null)
    | ({
        relationTo: 'plugin-ai-ai-jobs';
        value: number | PluginAiAiJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  artworkDescription?: T;
  artwork?: T;
  mockupDescription?: T;
  mockups?: T;
  price?: T;
  sizes?: T;
  colors?: T;
  fit?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions_select".
 */
export interface PluginAiInstructionsSelect<T extends boolean = true> {
  'schema-path'?: T;
  'field-type'?: T;
  'relation-to'?: T;
  hasMany?: T;
  'model-id'?: T;
  disabled?: T;
  alwaysShow?: T;
  appendGenerated?: T;
  prompt?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  system?: T;
  layout?: T;
  'text-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
        providerOptions?: T;
      };
  'richtext-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
        providerOptions?: T;
      };
  'image-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        providerOptions?: T;
      };
  'tts-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        voice?: T;
        providerOptions?: T;
      };
  'array-settings'?:
    | T
    | {
        provider?: T;
        model?: T;
        count?: T;
        providerOptions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-ai-jobs_select".
 */
export interface PluginAiAiJobsSelect<T extends boolean = true> {
  instructionId?: T;
  task_id?: T;
  status?: T;
  progress?: T;
  result_id?: T;
  error?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Connect your providers and choose the default models used across your project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-providers".
 */
export interface AiProvider {
  id: number;
  /**
   * Add one or more providers and set their credentials and settings. You can keep multiple providers and switch defaults below.
   */
  providers: (
    | {
        enabled?: boolean | null;
        /**
         * Optional. If empty, @ai-sdk/openai will use the OPENAI_API_KEY environment variable.
         */
        apiKey?: string | null;
        /**
         * Optional. Override default API endpoint (defaults to https://api.openai.com/v1).
         */
        baseURL?: string | null;
        /**
         * Optional. OpenAI organization ID for billing and access control.
         */
        organization?: string | null;
        /**
         * Optional. OpenAI project ID for organization-level access.
         */
        project?: string | null;
        /**
         * Optional. Extra headers to send with every request, for example routing through a proxy.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Available voices for Text-to-Speech models. You can add custom voices here.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
            }[]
          | null;
        /**
         * Keep this list short. Enable only the models you actually use.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: ('text' | 'image' | 'tts' | 'embedding') | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openai';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your Anthropic API key. Will be encrypted in the database.
         */
        apiKey: string;
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: 'text' | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'anthropic';
      }
    | {
        enabled?: boolean | null;
        /**
         * Optional. If empty, @ai-sdk/google will use the GOOGLE_GENERATIVE_AI_API_KEY environment variable.
         */
        apiKey?: string | null;
        /**
         * Optional. Override default API endpoint (defaults to https://generativelanguage.googleapis.com/v1beta).
         */
        baseURL?: string | null;
        /**
         * Optional. Extra headers to send with every request, for example routing through a proxy.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Available voices for Gemini TTS models.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
            }[]
          | null;
        /**
         * Keep this list short. Enable only the models you actually use.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: ('text' | 'image' | 'tts' | 'embedding') | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'google';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your xAI API key. Will be encrypted in the database.
         */
        apiKey: string;
        models?:
          | {
              id: string | null;
              name: string;
              useCase: 'text' | 'image';
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'xai';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your ElevenLabs API key. Will be encrypted in the database. Get yours at elevenlabs.io
         */
        apiKey: string;
        /**
         * Optional. Override default API endpoint (defaults to https://api.elevenlabs.io/v1).
         */
        baseURL?: string | null;
        /**
         * Optional. Custom headers to send with every request.
         */
        headers?:
          | {
              key: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Use the "Fetch Voices" button above to populate this list from your ElevenLabs account.
         */
        voices?:
          | {
              id: string | null;
              name: string;
              enabled?: boolean | null;
              category?: ('premade' | 'cloned' | 'professional' | 'generated') | null;
              preview_url?: string | null;
              /**
               * Voice attributes like gender, age, accent (JSON object). Example: {"gender": "female", "age": "young", "accent": "american"}
               */
              labels?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
            }[]
          | null;
        /**
         * Configure TTS models. Use the Voices and Provider Options tabs for detailed settings.
         */
        models?:
          | {
              id: string | null;
              name: string;
              useCase?: 'tts' | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'AUDIO')[] | null;
              enabled?: boolean | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'elevenlabs';
      }
    | {
        enabled?: boolean | null;
        /**
         * Your Fal API key. Will be encrypted in the database.
         */
        apiKey: string;
        /**
         * Secret for webhook verification (optional)
         */
        webhookSecret?: string | null;
        models?:
          | {
              id: string | null;
              name: string;
              useCase: 'image' | 'video';
              enabled?: boolean | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO')[] | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fal';
      }
    | {
        /**
         * Display name for this custom provider (e.g., "Ollama", "Together AI")
         */
        providerName: string;
        enabled?: boolean | null;
        /**
         * API key for this provider (if required)
         */
        apiKey: string;
        /**
         * OpenAI-compatible API endpoint (e.g., http://localhost:11434/v1)
         */
        baseURL: string;
        models?:
          | {
              id: string | null;
              name: string;
              useCase: 'text' | 'image' | 'video' | 'tts';
              enabled?: boolean | null;
              /**
               * Output capabilities of this model
               */
              responseModalities?: ('TEXT' | 'IMAGE' | 'AUDIO')[] | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openai-compatible';
      }
  )[];
  enabledCollections?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Pick the default provider and model for each feature. These defaults are used unless a collection or field overrides them.
   */
  defaults?: {
    text?: {
      provider?: string | null;
      model?: string | null;
      providerOptions?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      schema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    image?: {
      provider?: string | null;
      model?: string | null;
      providerOptions?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      schema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    tts?: {
      provider?: string | null;
      model?: string | null;
      voice?: string | null;
      providerOptions?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      schema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    video?: {
      provider?: string | null;
      model?: string | null;
      providerOptions?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      schema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-providers_select".
 */
export interface AiProvidersSelect<T extends boolean = true> {
  providers?:
    | T
    | {
        openai?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              organization?: T;
              project?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        anthropic?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        google?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        xai?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        elevenlabs?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              voices?:
                | T
                | {
                    id?: T;
                    name?: T;
                    enabled?: T;
                    category?: T;
                    preview_url?: T;
                    labels?: T;
                  };
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    responseModalities?: T;
                    enabled?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fal?:
          | T
          | {
              enabled?: T;
              apiKey?: T;
              webhookSecret?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                    responseModalities?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'openai-compatible'?:
          | T
          | {
              providerName?: T;
              enabled?: T;
              apiKey?: T;
              baseURL?: T;
              models?:
                | T
                | {
                    id?: T;
                    name?: T;
                    useCase?: T;
                    enabled?: T;
                    responseModalities?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  enabledCollections?: T;
  defaults?:
    | T
    | {
        text?:
          | T
          | {
              provider?: T;
              model?: T;
              providerOptions?: T;
              schema?: T;
            };
        image?:
          | T
          | {
              provider?: T;
              model?: T;
              providerOptions?: T;
              schema?: T;
            };
        tts?:
          | T
          | {
              provider?: T;
              model?: T;
              voice?: T;
              providerOptions?: T;
              schema?: T;
            };
        video?:
          | T
          | {
              provider?: T;
              model?: T;
              providerOptions?: T;
              schema?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}